### ISSUE TITLE
Ông vẫn đi học à?

### ISSUE THREAD

**Issue by ducphanduyagentp** [dungtran3864/swen-514-web-app#1]
?? :D ??

**Comment by dungtran3864** [comment]
uh :( ông còn đi học koo???

**Comment by ducphanduyagentp** [comment]
Tôi không :)) tốt nghiệp năm ngoái rồi :))

**Comment by dungtran3864** [comment]
Vl :) thế bây h ông đang đi làm ở đâu đấy? Còn ở Mỹ ko??
